spring:
  application:
    name: backend
  datasource:
    url: jdbc:mysql://localhost:3306/gamification_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      pool-name: HikariPool-gamification
      transaction-isolation: TRANSACTION_READ_COMMITTED
      auto-commit: false
      minimum-idle: 2
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect


# RabbitMQ Configuration
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
#    template:
#      exchange: gamification.exchange
#      routing-key: gamification.routingkey
#      default-receive-queue: gamification.queue

# PostgreSQL Configuration
# Uncomment below to use PostgreSQL instead of MySQL
#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/gamification_db
#    username: postgres
#    password: password
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:

  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    url: /v3/api-docs
  api-docs:
    path: /v3/api-docs  # Where OpenAPI JSON is served
    enabled: true


server:
  port: 8080
